---
- name: Install dependency cppcms
  apt:
    name: ['make', 'cmake', 'g++', 'libpcre3-dev', 'zlib1g-dev', 'libicu-dev']
    state: present

- name: Fetch cppcms source
  get_url: url=http://downloads.sourceforge.net/project/cppcms/cppcms/1.0.5/cppcms-1.0.5.tar.bz2 dest=/tmp/

- name: Extract source from the archive
  command: tar -jxvf cppcms-1.0.5.tar.bz2 chdir=/tmp/
  when: install_state is failed or force_install == true

- name: Disable testing
  replace:
    path: '/tmp/cppcms-1.0.5/CMakeLists.txt'
    regexp: "^(enable_testing\\(\\))$"
    replace: "#\\1"

- name: Generate makefile
  command: cmake . chdir=/tmp/cppcms-1.0.5

- name: Compile
  command: make -j2 chdir=/tmp/cppcms-1.0.5

- name: Install
  command: make install chdir=/tmp/cppcms-1.0.5

- name: Remove temporary files
  file:
    path: /tmp/cppcms-1.0.5
    state: absent

