---

- name: Fetch cppcmsskel source
  git: repo=https://github.com/allan-simon/cppcms-skeleton dest=/tmp/cppcmsskel

- name: Generate makefile
  command: cmake . chdir=/tmp/cppcmsskel

- name: Compile
  command: make chdir=/tmp/cppcmsskel

- name: Install
  command: make install chdir=/tmp/cppcmsskel

- name: Remove temporary files
  file:
    path: /tmp/cppcmsskel
    state: absent
